version: '3'

services:
  mysqlServer:
    image: mysql:5.6
    container_name: mysql_server_ifood
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ifood
      MYSQL_ROOT_HOST: '%'
    ports:
    - "3306:3306"

  documentation:
    image: nginx:latest
    container_name: "documentation"
    restart: always
    volumes:
    - ./doc-html:/usr/share/nginx/html
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80

  app:
    restart: always
    build: ./java
    working_dir: /app
    volumes:
      - ./java:/app
    ports:
      - "3000:3000"
    command: mvn clean spring-boot:run
    depends_on:
      - mysqlServer