services:
  weather:
    uri: http://api.openweathermap.org/data/2.5/weather
    id: 398b8ddf855a1fb8322da99648fb4ebc
    paths:
      city: ?APPID=${services.weather.id}&q={name}&units=metric
      coord: ?APPID=${services.weather.id}&lat={lat}&lon={lon}&units=metric
  spotify:
    token:
      uri: https://accounts.spotify.com
      path: api/token
    uri: https://api.spotify.com
    id: c724fa1199704f74b0f2b46b62408e2e
    secret: 17d962e5a2304d8383cfcbb84cc9e135

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        decode404: false

logging:
  level: DEBUG