openWeather:
    key: "test-key"
    endpoint: "http://localhost:8089/weather"

spotify:
    playlistEndpoint: "http://localhost:8089/spotify/%s/playlists"
    tracksEndpoint: "http://localhost:8089/spotify/playlists/%s/tracks"

cache:
    evictTime: 1