openWeather:
    key: "d789f4c1287eddab12a774a816e6e8d7"
    endpoint: "http://api.openweathermap.org/data/2.5/weather"

spotify:
    playlistEndpoint: "https://api.spotify.com/v1/browse/categories/%s/playlists"
    tracksEndpoint: "https://api.spotify.com/v1/users/spotify/playlists/%s/tracks"

cache:
    evictTime: 3600

spring:
    jackson:
        property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategy.SnakeCaseStrategy