# config port server
server:
  contextPath:
  port: 8080

api:
  key:
    openWeatherMap: 4aaeb0f31237b8fd2065b00e9ee4ec2c
    spotify:
      url:
        token: https://accounts.spotify.com/api/token
      client:
        id: 02ad3a54435b495f90f1e9eef4073b59
        secret: 37b1707f6744404abdc1b9705ccee9f1
      authorization:
        base64: Basic MDJhZDNhNTQ0MzViNDk1ZjkwZjFlOWVlZjQwNzNiNTk6MzdiMTcwN2Y2NzQ0NDA0YWJkYzFiOTcwNWNjZWU5ZjE=
      redirect:
        url: http://localhost:8080

spring:
  data:
    mongodb:
      database: iTemper # Database name.
#      # field-naming-strategy: # Fully qualified name of the FieldNamingStrategy to use.
#      #grid-fs-database: # GridFS database name.
#      host: localhost # Mongo server host.
#      # password: # Login password of the mongo server.
#      port: 27017 # Mongo server port.
#      repositories:
#        enabled: true # Enable Mongo repositories.
#      uri: mongodb://localhost/maisVida # Mongo database URI. When set, host and port are ignored.
#      # username: # Login user of the mongo server.